version: '3'
services:
  regards-doc-generator:
    image: "${DOCKER_REGISTRY}regards-doc-generator:${TAG}"
    command: bash -c "rm -rf _site && jekyll serve --livereload --incremental --trace"
    build:
      context: ./
      args:
        - http_proxy
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
