module.exports = {
  overview: [
    {
      type: 'autogenerated',
      dirName: 'overview',
    }
  ],
  install: [
    {
      type: "category",
      label: "Installation - Docker Swarm",
      items: [
        {
          type: 'autogenerated',
          dirName: 'setup/swarm',
        },
      ],
    },
    {
      type: "category",
      label: "Playbook Guide",
      items: [
        {
          type: 'autogenerated',
          dirName: 'setup/playbook',
        },
      ],
    },
  ],
  manual: [
    {
      type: "category",
      label: "Overview",
      items: [
        "user-documentation/overview/overview",
        "user-documentation/overview/glossary",
      ],
    },
    {
      type: "category",
      label: "Start with REGARDS concepts",
      items: [
        "user-documentation/z2_concept/tenant-overview",
        "user-documentation/z2_concept/database-overview",
        "user-documentation/z2_concept/configuration-overview",
      ],
    },
    {
      type: "category",
      label: "Administrator configuration",
      items: [
        "user-documentation/global-configuration/global-configuration-introduction",
        "user-documentation/global-configuration/global-configuration-portal",
        "user-documentation/global-configuration/global-configuration-projects",
        "user-documentation/global-configuration/global-configuration-users",
      ],
    },
    {
      type: "category",
      label: "Project configuration",
      items: [
        "user-documentation/project-configuration/project-configuration-introduction",
        "user-documentation/project-configuration/project-configuration-users",
        {
          type: "category",
          label: "Manage authentications",
          items: [
            "user-documentation/project-configuration/project-configuration-users-authentication",
            "user-documentation/project-configuration/project-configuration-users-authentication-openid",
            "user-documentation/project-configuration/project-configuration-users-authentication-ldap",
          ],
        },
        "user-documentation/project-configuration/project-configuration-user-interface",
        "user-documentation/project-configuration/project-configuration-microservices",
        "user-documentation/project-configuration/project-configuration-storages",
        "user-documentation/project-configuration/notifier-configuration",
      ],
    },

    {
      type: "category",
      label: "Data organization",
      items: [
        "user-documentation/data-organization/data-organization-introduction",
        "user-documentation/data-organization/data-organization-model-configuration",
        "user-documentation/data-organization/data-organization-collections-datasets",
        "user-documentation/data-organization/data-organization-data-access-rights",
      ],
    },
    {
      type: "category",
      label: "Build your scientific archive",
      items: [
        "user-documentation/import-data/import-data-introduction",
        {
          type: "category",
          label: "Build OAIS archive",
          items: [
            "user-documentation/4_1-ingest/oais-files-introduction",
            "user-documentation/4_1-ingest/oais-files-configure-ingestion-chains",
            "user-documentation/4_1-ingest/oais-files-submit-products",
            "user-documentation/4_2-dataprovider/scanned-files-manage-acquisition-chains",
            "user-documentation/4_1-ingest/oais-files-manage-products",
            "user-documentation/4_1-ingest/oais-files-settings",
            "user-documentation/4_1-ingest/oais-dissemination",
          ],
        },
        {
          type: "category",
          label: "Build GeoJson Feature archive",
          items: [
            "user-documentation/4_3-fem/fem-introduction",
            "user-documentation/4_3-fem/fem-manage-features",
            "user-documentation/4_3-fem/fem-features-dissemination",
            "user-documentation/4_3-fem/fem-settings",
          ],
        }
      ],
    },
    {
      type: "category",
      label: "Build your catalog",
      items: [
        "user-documentation/crawler/crawler-introduction",
        "user-documentation/crawler/crawler-configure-connection",
        {
          type: "category",
          label: "Configure datasources",
          items: [
            "user-documentation/crawler/crawler-configure-datasources",
            "user-documentation/crawler/crawler-external-databases",
            "user-documentation/crawler/crawler-opensearch",
            "user-documentation/crawler/crawler-aips",
            "user-documentation/crawler/crawler-fem",
          ],
        },
        "user-documentation/crawler/crawler-monitor-crawling",
        "user-documentation/crawler/crawler-reset-catalog",
        "user-documentation/crawler/crawler-elasticsearch-shard",
      ],
    },
    {
      type: "category",
      label: "Browse catalog",
      items: [
        "user-documentation/catalog-consultation/catalog-introduction",
        "user-documentation/catalog-consultation/catalog-configuration",
        "user-documentation/catalog-consultation/catalog-use",
        "user-documentation/catalog-consultation/catalog-toponyms",
        {
          type: "category",
          label: "Interoperability protocols",
          items: [
            "user-documentation/catalog-consultation/catalog-protocols-intro",
            "user-documentation/catalog-consultation/catalog-protocols-opensearch",
            "user-documentation/catalog-consultation/catalog-protocols-stac",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Data services",
      items: [
        "user-documentation/data-services/data-services-introduction",
        "user-documentation/data-services/data-services-ui-services",
        "user-documentation/data-services/data-services-processing-services",
      ],
    },
    {
      type: "category",
      label: "Order data",
      items: [
        "user-documentation/order-data/order-introduction",
        "user-documentation/order-data/order-manage-orders",
        "user-documentation/order-data/file-filters",
        "user-documentation/order-data/order-processing",
        "user-documentation/order-data/order-monitor-orders",
        "user-documentation/order-data/order-settings",
      ],
    },
    {
      type: "category",
      label: "Monitoring",
      items: [
        "user-documentation/monitoring/dashboard"
      ],
    }
  ],
  dev: [
    "development/development-manual",
    {
      type: "category",
      label: "Concepts",
      items: [
        {
          type: 'autogenerated',
          dirName: 'development/concepts',
        },
      ],
    },
    {
      type: "category",
      label: "Services",
      items: [
        "development/services/services-overview",
        {
          "Common": [
            {
              type: 'autogenerated',
              dirName: 'development/services/common'
            }
          ]
        },
        {
          "Access project": [
            {
              type: 'autogenerated',
              dirName: 'development/services/access-project'
            }
          ]
        }, 
        {
          "Authentication": [
            {
              type: 'autogenerated',
              dirName: 'development/services/authentication'
            }
          ]
        },
        {
          "Config": [
            {
              type: 'autogenerated',
              dirName: 'development/services/config',
            }
          ],
        },
        {
          "Catalog": [
            {
              type: 'autogenerated',
              dirName: 'development/services/catalog',
            }
          ],
        },
        {
          "Data Manager (rs-dam)": [
            {
              type: 'autogenerated',
              dirName: 'development/services/dam',
            }
          ]
        },
        {
          "Data provider": [
            {
                type: 'autogenerated',
                dirName: 'development/services/delivery'
            }
           ]
        },
        {
            "Ingest": [
            {
              type: 'autogenerated',
              dirName: 'development/services/ingest'
            }
          ]
        },
        {
          "Gateway": [
            {
              type: 'autogenerated',
              dirName: 'development/services/gateway',
            }
          ]
        },
        {
          "Feature manager (rs-fem)": [
            {
              type: 'autogenerated',
              dirName: 'development/services/fem',
            }
          ]
        },
        {
          "Ingest": [
            {
              type: 'autogenerated',
              dirName: 'development/services/lta-manager'
            }
          ]
        },
        {
          "Notifier": [
            {
              type: 'autogenerated',
              dirName: 'development/services/notifier',
            }
          ]
        },
        {
          "Order": [
            {
              type: 'autogenerated',
              dirName: 'development/services/order',
            }
          ]
        },
        {
          "Processing": [
            {
              type: 'autogenerated',
              dirName: 'development/services/processing',
            }
          ]
        },
        {
          "Registry": [
            {
              type: 'autogenerated',
              dirName: 'development/services/registry',
            }
          ],
        },
        {
          "Storage": [
            {
              type: 'autogenerated',
              dirName: 'development/services/storage',
            }
          ],
        },
        {
          "Worker Manager": [
            {
              type: 'autogenerated',
              dirName: 'development/services/worker-manager',
            }
          ],
        }
      ],
    },
    {
      type: "category",
      label: "Framework",
      items: [
        {
          type: 'autogenerated',
          dirName: 'development/framework',
        },
      ],
    },
    {
      type: "category",
      label: "Web HMI",
      items: [
        {
          type: "category",
          label: "Introduction",
          items: [
            "development/frontend/frontend-introduction-setup",
            "development/frontend/frontend-introduction-ide",
            "development/frontend/frontend-introduction-architecture",
            "development/frontend/frontend-introduction-eslint",
            "development/frontend/frontend-introduction-index",
          ],
        },
        {
          type: "category",
          label: "Data",
          items: [
            "development/frontend/frontend-data-ui",
            "development/frontend/components/frontend-data-clients",
          ],
        },
        {
          type: "category",
          label: "View",
          items: [
            "development/frontend/components/frontend-view-international",
            "development/frontend/components/frontend-view-theme",
            "development/frontend/components/frontend-view-forms",
          ],
        },
        {
          type: "category",
          label: "Packages",
          items: [
            "development/frontend/components/frontend-packages-components",
            {
              type: "category",
              label: "Business components",
              items: [
                "development/frontend/components/frontend-packages-business-components",
                "development/frontend/components/business/frontend-packages-business-components-microservice-plugin",
              ]
            },
            {
              type: "category",
              label: "Lazy modules",
              items: [
                "development/frontend/modules/frontend-packages-lazy-modules",
                "development/frontend/modules/frontend-packages-lazy-modules-authentication",
                "development/frontend/modules/frontend-packages-lazy-modules-embedded-html",
                "development/frontend/modules/frontend-packages-lazy-modules-licenses",
                "development/frontend/modules/frontend-packages-lazy-modules-menu",
                "development/frontend/modules/frontend-packages-lazy-modules-order-cart",
                "development/frontend/modules/frontend-packages-lazy-modules-order-history",
                "development/frontend/modules/frontend-packages-lazy-modules-project-about-page",
                "development/frontend/modules/frontend-packages-lazy-modules-project-list",
                "development/frontend/modules/frontend-packages-lazy-modules-search-graph",
                "development/frontend/modules/frontend-packages-lazy-modules-search-results"
              ]
            }
          ],
        },
        {
          type: "category",
          label: "Plugins",
          items: [
            "development/frontend/plugins/frontend-plugins",
            "development/frontend/plugins/frontend-criteria-plugins",
            "development/frontend/plugins/frontend-service-plugins",
          ],
        },
        {
          type: "category",
          label: "Configuration",
          items: ["development/frontend/frontend-configuration-layout"],
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [
        {
          type: 'autogenerated',
          dirName: 'development/tutorials',
        },
      ]
    },
    {
      type: "category",
      label: "Appendices",
      items: [
        {
          type: 'autogenerated',
          dirName: 'development/appendices',
        },
      ],
    },
  ]
};
