@startuml

interface PProject
class PBatch
class PExecution
class PStep
class PInputFile
class POutputFile

PProject *-- PBatch
PBatch *-- PExecution
PExecution *-- PStep
PExecution *-- PInputFile
PExecution *-- POutputFile
POutputFile *-- PInputFile

@enduml